name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}} 
    - name: Build lib
      run: dotnet pack src/TestLib/TestLib.csproj -c Release /p:PackageVersion=1.0.0-ci.$BUILD_NUMBER -o $(pwd)/packages
    - name: Push to packages
      run: dotnet nuget push packages/TestLib.1.0.0-ci.$BUILD_NUMBER.nupkg -s "https://nuget.pkg.github.com/SonicGD/index.json" -k ${{secrets.ACTIONS_TOKEN}} \;
