name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    - name: Upload build number
      uses: actions/upload-artifact@v1
      with:
        name: BUILD_NUMBER
        path: BUILD_NUMBER
   
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download build number
      uses: actions/download-artifact@v1
      with:
        name: BUILD_NUMBER
    - name: Restore build number
      id: buildnumber
      uses: einaregilsson/build-number@v1 
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Build lib
      run: dotnet pack src/TestLib/TestLib.csproj -c Release /p:PackageVersion=1.0.0-ci.$BUILD_NUMBER -o $(pwd)/packages
    - name: Add nuget source
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/SonicGD/index.json" -UserName SonicGD -Password ${{secrets.github_token}}
    - name: Push to packages
      run: nuget push packages/TestLib.1.0.0-ci.$BUILD_NUMBER.nupkg -Source "GPR"
